unstable_features = true

blank_lines_upper_bound = 2
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
format_strings = true

match_block_trailing_comma = true
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 15
enum_discrim_align_threshold = 15
wrap_comments = true
hard_tabs = true
format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"
